# Generated by Django 4.2.6 on 2023-10-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_biography_person_birthdate_person_birthplace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='biography',
            new_name='overview',
        ),
    ]
