# Generated by Django 4.2.6 on 2023-10-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_photo_url_person_profile_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_path',
        ),
    ]
