# Generated by Django 4.2.6 on 2023-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_person_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file_path',
            field=models.URLField(blank=True),
        ),
    ]
