# Generated by Django 4.2.6 on 2023-10-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_person_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_path',
            field=models.URLField(blank=True),
        ),
    ]
